### PR TITLE
Compilable voting contract

### PR DESCRIPTION
**Pull request by marqed2**
- Batch proposal
- 24h lock time after submission of batch proposal
- Endvote function
- Add math funtions to Math contract of openzepplin
- - Quorum is just a simple majority no categories

### CODE REVIEW

**Comment by yunjieee** [comment]
I will approve it to help you push this process

**Comment by ca-lida** [comment]
@marqed2 
thoughts on NATSPECC-ing all the functions?

**Review by Naopod — APPROVED** [review]
Seems easier, let's try it out !

**Comment by ca-lida** [comment]
Also, can you rename your read me file to read me - governance? We'll combine yours with ours for the technical bit at the end.

**Comment by YurenJeremyJin** [comment]
I just resolve the readme file's conflict, after reviewing it should be ready to merge to main

**Comment by marqed2** [comment]
> Also, can you rename your read me file to read me - governance? We'll combine yours with ours for the technical bit at the end.

**Comment by marqed2** [comment]
> @marqed2 thoughts on NATSPECC-ing all the functions?

Added on my new pull request 16#

**Comment by marqed2** [comment]
> Also, can you rename your read me file to read me - governance? We'll combine yours with ours for the technical bit at the end.

amended on my new pull reques #16

**Comment by marqed2** [comment]
Calida comments taken into account in pull request #16

**Pull request closed without merging**
