### PR TITLE
Major changes: changing token

### PR DESCRIPTION
**Pull request by vallathortense**

### CODE REVIEW

**Comment by vallathortense** [comment]
Toke team please go have a look on it !!

**Comment by Matthieu-z-David** [comment]
Code reviewed, good structure 
- just _transfer has a compiling alert

**Comment by vallathortense** [comment]
@Matthieu-z-David indeed ! thanks for the code ! now it should be good. The forge test ran successfully

**Review by vallathortense — COMMENTED** [review]
@Matthieu-z-David could you merge it to the Token branch please ?

**Pull request merged**
